
development:
  adapter: postgresql
  encoding: utf8
  database: HappyFish_dev
  pool: 5
  username: hfh
  password: hfH001

test:
  adapter: postgresql
  encoding: utf8
  database: HappyFish_test
  pool: 5
  username: hfh
  password: hfH001

production:
  adapter: postgresql
  encoding: utf8
  database: HappyFish_prod
  pool: 5
  username: hfh
  password: hfH001

